kind: Deployment
apiVersion: apps/v1
metadata:
  name: cicd-sample
spec:
  replicas: 2
  selector:
    matchLabels:
      env: production
  template:
    metadata:
      name: cicd-sample
      labels:
        env: production
    spec:
      containers:
      - name: cicd-sample
        resources:
          limits:
            memory: "128Mi"
            cpu: "250m"
        env:
        - name: VERSION
          value: prod
