apiVersion: skaffold/v2beta16
kind: Config
metadata:
  name: full-stack
build:
  artifacts:
  - image: cicd-sample
    context: ./
test:
  - image: cicd-sample
    custom:
      - command: ./test.sh
        timeoutSeconds: 60
        dependencies:
          paths:
          -  "*_test.go"
          -  "test.sh"
      - command: echo Hello world!!
        dependencies:
          command: echo [\"main_test.go\"]
deploy:
  kustomize:
    paths:
    - k8s/dev/
portForward:
- resourceType: service
  resourceName: cicd-sample
  port: 8080
profiles:
- name: staging
  deploy:
    kustomize:
      paths:
      - k8s/staging/
- name: prod
  deploy:
    kustomize:
      paths:
      - k8s/prod/
