kind: Deployment
apiVersion: apps/v1
metadata:
  name: cicd-sample
spec:
  selector:
    matchLabels:
      app: cicd-sample
      env: base
  template:
    metadata:
      name: cicd-sample
      labels:
        app: cicd-sample
        env: base
    spec:
      containers:
      - name: cicd-sample
        image: cicd-sample
        resources:
          limits:
            memory: "128Mi"
            cpu: "250m"
        env:
        - name: VERSION
          value: base
        imagePullPolicy: Always
        livenessProbe:
          initialDelaySeconds: 10
          periodSeconds: 10
          httpGet:
            path: /healthz
            port: 8080
        readinessProbe:
          initialDelaySeconds: 2
          periodSeconds: 20
          httpGet:
            path: /healthz
            port: 8080
        ports:
        - name: cicd-sample
          containerPort: 8080
      securityContext:
        runAsUser: 1000
        runAsNonRoot: true
